### ISSUE TITLE
Funcion not executing

### ISSUE THREAD

**Issue by diamaria** [diamaria/LearnToCode#1]
document.getElementByID("p14").innerHTML = pos3;

**Comment by mkandut** [comment]
Please check Chrome Dev Tools. 
`AtoZ.js:56 Uncaught TypeError: document.getElementByID is not a function at window.onload (AtoZ.js:56)`

Checking and fixing

**Comment by mkandut** [comment]
fixed, see pull request  #2.

**Comment by mkandut** [comment]
You can also host static pages on github, very interesting for projects like this. [Github Pages](https://pages.github.com/) 

And this issue can be closed. wanna close it? @diamaria
