### ISSUE TITLE
Replace cats /i case insensitive doesn't work

### ISSUE THREAD

**Issue by diamaria** [diamaria/LearnToCode#3]
<p id="p20"></p>
Pls help :)

**Comment by mkandut** [comment]
The regex documentation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) is very helpful. You can combine flags like g or i to '/cats/gi'.

**Comment by mkandut** [comment]
see this commit 84da6d5ae964d8df6107a2f990f5a3d3491a20d1. I've commited direct to master so no merge is needed. 💯

**Comment by diamaria** [comment]
:D Very helpful, as always! Thank you!
